version: "3.8"

services:
  api_app:
    container_name: forecast_api_app
    build:
      context: ./404-forecast-not-found-api-app
      dockerfile: docker/php/Dockerfile
    expose:
      - "9000"
    volumes:
      - ./404-forecast-not-found-api-app:/var/www
    networks:
      - forecast-network
    depends_on:
      - db
      - cache

  frontend_app:
    container_name: forecast_frontend_app
    build:
      context: ./404-forecast-frontend-app
      dockerfile: docker/php/Dockerfile
    expose:
      - "9000"
    volumes:
      - ./404-forecast-frontend-app:/var/www
    networks:
      - forecast-network

  gateway:
    container_name: forecast_gateway
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./404-forecast-frontend-app:/var/www/frontend-app:ro
      - ./404-forecast-not-found-api-app:/var/www/backend-api:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend_app
      - api_app
    networks:
      - forecast-network

  db:
    image: mysql:8.0
    container_name: forecast_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: forecast_db
      MYSQL_USER: forecast_user
      MYSQL_PASSWORD: forecast_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - forecast-network

  cache:
    image: redis:alpine
    container_name: forecast_redis
    ports:
      - "6379:6379"
    networks:
      - forecast-network

networks:
  forecast-network:
    driver: bridge

volumes:
  mysql_data:
